name: Actions Workflow
on: [push]
jobs:
  run-gihub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Crisz
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
